version: '2'
services:
  camera:
    image: alexstreet/cato-camera:jessie
    ports:
     - "8080:8080"
    network_mode: host
    privileged: true
    restart: always
  movement:
    image: alexstreet/cato-camera-movement:v4
    network_mode: host
    depends_on:
     - camera
    environment:
     - input_url=http://192.168.0.1:8080/?action=snapshot
     - output_url=http://192.168.0.1:5001/api/image/
     - camera_name=cam1
     - threshold=10000
     - mqenabled=Y
     - mqserver=192.168.0.1
     - mqq=msg_gateway
    restart:always
